name: manydepth
channels:
  - default
  - pytorch
  - conda-forge
dependencies:
  - opencv
  - matplotlib
  - pytorch==1.11.0
  - torchvision==0.12.0
  - scikit-image==0.19.3
  # - opencv=3.4.2
  # - matplotlib=3.1.2
  - numpy=1.19.5
  - pip
  - pip:
    - Pillow==6.2.1
    - tensorboardX==1.5
    # - scikit-image==0.16.2
    # - torch==1.7.1
    # - torchvision==0.8.2
    - tqdm==4.57.0
